spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://127.0.0.1:9000"
      client:
        registration:
          client-app:
            provider: spring
            client-id: MP_uGc9BGOKoL
            client-secret: vBZLv43Kkkzsm3xsljt0F3qAHb_9WKcmc8bItkyxABdW0KA9g8
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope:
              - openid
              - profile
              - read
              - write
            client-name: MP_uGc9BGOKoL
        provider:
          spring:
            issuer-uri: "http://127.0.0.1:9000"